FROM node:18-slim

# 1. Instalar o Google Chrome e dependências do sistema
# Isso é obrigatório para o whatsapp-web.js rodar no servidor
RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# 2. Definir diretório de trabalho
WORKDIR /usr/src/app

# 3. Copiar arquivos do projeto
COPY package*.json ./
RUN npm install

COPY . .

# 4. Variável para pular o download do Chromium (já instalamos o Chrome acima)
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

# 5. Comando para iniciar
CMD [ "node", "index.js" ]